blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussion
    url: https://github.com/segnities007/dotnet/discussions
    about: è³ªå•ã‚„ãƒ‡ã‚£ã‚¹ã‚«ãƒƒã‚·ãƒ§ãƒ³ã¯ã“ã¡ã‚‰
  - name: ğŸ“– Documentation
    url: https://github.com/segnities007/dotnet/blob/main/doc/ARCHITECTURE.md
    about: ãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆã®ã‚¢ãƒ¼ã‚­ãƒ†ã‚¯ãƒãƒ£ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆ
